//! Protocol byte-fixture tests: the messages Outh sends must be
//! BYTE-IDENTICAL to the messages gotohp sends, because the server-side
//! contract is the wire bytes (field numbers from `.proto/*.proto`, values
//! from `core/api.go`), not any schema semantics.
//!
//! Every expected byte string below is derived TWICE, independently:
//!   1. hand-computed from the `.proto` field numbers + the construction
//!      code in gotohp `core/api.go` (derivation shown in comments), and
//!   2. generated by the real Go code — `tools/gen-fixtures` marshals the
//!      same messages with gotohp's generated protobuf types; its output is
//!      committed at `tests/fixtures/golden.txt` and cross-checked by
//!      `golden_file_matches_hand_derived_fixtures` below.
//! Both derivations agree on every fixture.
//!
//! ============================================================================
//! API — as landed in `outh_core::protocol` (adapted at integration):
//!
//! * Types live in `outh_core::protocol`, named after the `.proto` messages
//!   (PascalCase): GetUploadToken, HashCheck, CommitUpload, CommitToken,
//!   CreateAlbum, AddMediaToAlbum, RemoteMatches, CreateAlbumResponse,
//!   CreateMediaItemsResponse, ScottyToken.
//! * Nested message types are named `<Parent><ProtoFieldName>` WITHOUT the
//!   "Type" suffix Go's generator appends (Go: `HashCheckField1Type` →
//!   here: `HashCheckField1`). The device block shared by CommitUpload
//!   field 2, CreateAlbum field 8 and AddMediaToAlbum field 6 is the
//!   single protocol type `DeviceInfo`.
//! * Encoding follows CONTRACT.md exactly: `encode(&self, &mut Vec<u8>)`.
//! * Decoding is an associated function
//!   `decode(bytes: &[u8]) -> Result<Self, outh_core::Error>`.
//! * Message-typed struct fields are `Option<_>`; struct literals below
//!   wrap the fields gotohp sets in `Some(...)`. CommitUpload's field-1
//!   message also carries proto fields 8 (raw bytes, `None` — Go never
//!   constructs it) and 17 (varint, `0` — omitted on the wire).
//! * Struct field names are the proto field names in snake_case
//!   (`file_size_bytes`, `sha1_hash`, `file_name`, ...); the unnamed
//!   `fieldN` proto fields keep their `fieldN` names.
//! * `ScottyToken::parse(&[u8]) -> Result<ScottyToken, Error>` +
//!   `raw(&self) -> &[u8]` mirror Go's `ParseScottyFinalizeToken` and
//!   the opaque `Raw` field (core/scotty_token.go).
//! * `RemoteMatches::media_key() -> Option<&str>` and
//!   `CreateMediaItemsResponse::first_media_key() -> Option<&str>`
//!   mirror the hand-written Go helpers (`generated/utils.go GetMediaKey`,
//!   `core/api.go parseCreateMediaItemsResponse`).
//! ============================================================================

use outh_core::protocol::{
    AddMediaToAlbum, AddMediaToAlbumField5, CommitToken, CommitUpload, CommitUploadField1,
    CommitUploadField4, CreateAlbum, CreateAlbumField4, CreateAlbumField4Field1, CreateAlbumField6,
    CreateAlbumField7, CreateMediaItemsResponse, DeviceInfo, GetUploadToken, HashCheck,
    HashCheckField1, HashCheckField1Field1, HashCheckField1Field2, RemoteMatches, ScottyToken,
};

// ---- Fixed inputs (shared verbatim with tools/gen-fixtures/main.go) ----

/// SHA-1 of the empty string — a recognisable fixed 20-byte hash.
const SHA1_EMPTY: [u8; 20] = [
    0xda, 0x39, 0xa3, 0xee, 0x5e, 0x6b, 0x4b, 0x0d, 0x32, 0x55, 0xbf, 0xef, 0x95, 0x60, 0x18, 0x90,
    0xaf, 0xd8, 0x07, 0x09,
];
const OPAQUE_TOKEN: [u8; 4] = [0xde, 0xad, 0xbe, 0xef];
const FILE_NAME: &str = "IMG_0001.jpg";
const FILE_SIZE: i64 = 123_456_789;
const TIMESTAMP: i64 = 1_700_000_000;
/// core/api.go CommitUpload: `unknownInt := int64(46000000)` (magic, unexplained upstream).
const UNKNOWN_INT: i64 = 46_000_000;

// ---- Hand-derived expected bytes -------------------------------------------
//
// Protobuf wire refresher: tag = varint(field_number << 3 | wire_type);
// wire type 0 = varint, 2 = length-delimited (tag, varint length, bytes).
// Go's proto.Marshal emits fields in field-number order and omits
// zero-valued scalars, matching the derivations below.

/// GetUploadToken (.proto/GetUploadToken.proto; core/api.go GetUploadToken
/// sets F1=2, F2=2, F3=1, F4=3 unconditionally):
///   08 02          field 1 varint 2
///   10 02          field 2 varint 2
///   18 01          field 3 varint 1
///   20 03          field 4 varint 3
///   38 95 9a ef 3a field 7 varint 123456789 (0x075BCD15, little-endian 7-bit groups)
const GET_UPLOAD_TOKEN_HEX: &str = "080210021801200338959aef3a";

/// HashCheck (.proto/HashCheck.proto; core/api.go FindRemoteMediaByHash):
///   0a 1a                            outer field 1, len 26
///      0a 16                         inner field 1, len 22
///         0a 14 <20 bytes sha1>      innermost field 1, len 20
///      12 00                         inner field 2, len 0 (empty message — present!)
const HASH_CHECK_HEX: &str =
    "0a1a0a160a14da39a3ee5e6b4b0d3255bfef95601890afd807091200";

/// CommitToken (.proto/CommitToken.proto) = the Scotty finalize envelope:
///   08 02                field 1 varint 2 (the version; scotty_token.go)
///   12 04 de ad be ef    field 2 bytes, opaque payload
const COMMIT_TOKEN_HEX: &str = "08021204deadbeef";

/// CommitUpload (.proto/CommitUpload.proto; core/api.go CommitUpload,
/// default quality): see the field-by-field build in `commit_upload_bytes`.
/// Total 91 bytes; field 1 submessage is 0x3f = 63 bytes:
///   token {08 02, 12 04 deadbeef} = 8; file_name 0x0c+12 = 14;
///   sha1 0x14+... (1 tag + 1 len + 20) = 22; field4 (1+1+ (1+5)+(1+4)) = 13;
///   quality (1+1) = 2; field10 (1+1) = 2 → but with outer tags: 10+16+24+15+2+2
///   counted with their own tags inside the 63-byte submessage = 63. ✓
const COMMIT_UPLOAD_HEX: &str = "0a3f0a0808021204deadbeef120c494d475f303030312e6a70671a14da39a3ee5e6b4b0d3255bfef95601890afd80709220b0880e2cfaa061080cff7153803500112141a08506978656c20584c2206476f6f676c65281c1a020103";

/// Same, Saver mode: quality 3 → 1 and device model "Pixel XL" → "Pixel 2"
/// (one byte shorter, so the field-2 submessage length drops 0x14 → 0x13).
const COMMIT_UPLOAD_SAVER_HEX: &str = "0a3f0a0808021204deadbeef120c494d475f303030312e6a70671a14da39a3ee5e6b4b0d3255bfef95601890afd80709220b0880e2cfaa061080cff7153801500112131a07506978656c20322206476f6f676c65281c1a020103";

/// CreateAlbum (.proto/CreateAlbum.proto; core/api.go CreateAlbum with the
/// wall-clock timestamp pinned to TIMESTAMP):
///   0a 0a "Test Album"  field 1
///   10 80 e2 cf aa 06   field 2 varint 1700000000
///   18 01               field 3 varint 1
///   22 0d {0a 0b {0a 09 "MEDIAKEY1"}}  field 4, one media key wrapper
///   32 00               field 6, empty message
///   3a 02 {08 03}       field 7 { field 1 varint 3 }
///   42 14 {device}      field 8 device info (model 3, make 4, api 5)
const CREATE_ALBUM_HEX: &str = "0a0a5465737420416c62756d1080e2cfaa061801220d0a0b0a094d454449414b45593132003a02080342141a08506978656c20584c2206476f6f676c65281c";

/// AddMediaToAlbum (.proto/AddMediaToAlbum.proto; core/api.go
/// AddMediaToAlbum, timestamp pinned):
///   0a 09 "MEDIAKEY1"  0a 09 "MEDIAKEY2"   field 1 repeated
///   12 08 "ALBUMKEY"                        field 2 album key
///   2a 02 {08 02}                           field 5 { field 1 varint 2 }
///   32 14 {device}                          field 6 device info
///   38 80 e2 cf aa 06                       field 7 varint timestamp
const ADD_MEDIA_TO_ALBUM_HEX: &str = "0a094d454449414b4559310a094d454449414b4559321208414c42554d4b45592a02080232141a08506978656c20584c2206476f6f676c65281c3880e2cfaa06";

/// RemoteMatches response (.proto/RemoteMatches.proto): the media key lives
/// at field1.field2.field2.field1 (generated/utils.go GetMediaKey).
const REMOTE_MATCHES_HEX: &str =
    "0a2712250a160a14da39a3ee5e6b4b0d3255bfef95601890afd80709120b0a094d454449414b455931";

/// CreateMediaItemsResponse: item(1) { result_item(3) { media_key(1) } }.
const CREATE_MEDIA_ITEMS_RESPONSE_HEX: &str = "0a0d1a0b0a094d454449414b455931";

/// CreateAlbumResponse: field1 { album_media_key(1) = "ALBUMKEY" }.
const CREATE_ALBUM_RESPONSE_HEX: &str = "0a0a0a08414c42554d4b4559";

// ---- Helpers ----------------------------------------------------------------

fn hex_decode(s: &str) -> Vec<u8> {
    assert!(s.len() % 2 == 0, "hex string must have even length");
    (0..s.len() / 2)
        .map(|i| u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).expect("valid hex"))
        .collect()
}

fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn device_info() -> DeviceInfo {
    DeviceInfo {
        model: "Pixel XL".to_string(),
        make: "Google".to_string(),
        android_api_version: 28,
    }
}

fn commit_upload(quality: i64, model: &str) -> CommitUpload {
    // Mirrors core/api.go CommitUpload field-for-field.
    let mut device = device_info();
    device.model = model.to_string();
    CommitUpload {
        field1: Some(CommitUploadField1 {
            // The token field is the legacy CommitToken message itself.
            field1: Some(CommitToken {
                field1: 2,
                field2: OPAQUE_TOKEN.to_vec(),
            }),
            file_name: FILE_NAME.to_string(),
            sha1_hash: SHA1_EMPTY.to_vec(),
            field4: Some(CommitUploadField4 {
                file_last_modified_timestamp: TIMESTAMP,
                field2: UNKNOWN_INT,
            }),
            quality,
            field8: None,
            field10: 1,
            field17: 0,
        }),
        field2: Some(device),
        field3: vec![1, 3],
    }
}

// ---- Encode fixtures ----------------------------------------------------------

#[test]
fn get_upload_token_bytes_match_go() {
    let msg = GetUploadToken {
        f1: 2,
        f2: 2,
        f3: 1,
        f4: 3,
        file_size_bytes: FILE_SIZE,
    };
    let mut buf = Vec::new();
    msg.encode(&mut buf);
    assert_eq!(hex_encode(&buf), GET_UPLOAD_TOKEN_HEX);
}

#[test]
fn hash_check_bytes_match_go() {
    let msg = HashCheck {
        field1: Some(HashCheckField1 {
            field1: Some(HashCheckField1Field1 {
                sha1_hash: SHA1_EMPTY.to_vec(),
            }),
            // The empty second message MUST be emitted (len 0), exactly as
            // Go's non-nil &HashCheckField1TypeField2Type{} is.
            field2: Some(HashCheckField1Field2 {}),
        }),
    };
    let mut buf = Vec::new();
    msg.encode(&mut buf);
    assert_eq!(hex_encode(&buf), HASH_CHECK_HEX);
}

#[test]
fn commit_upload_bytes_match_go() {
    let mut buf = Vec::new();
    commit_upload(3, "Pixel XL").encode(&mut buf);
    assert_eq!(hex_encode(&buf), COMMIT_UPLOAD_HEX);
}

#[test]
fn commit_upload_saver_bytes_match_go() {
    // Saver mode (core/api.go): quality = 1, model forced to "Pixel 2".
    let mut buf = Vec::new();
    commit_upload(1, "Pixel 2").encode(&mut buf);
    assert_eq!(hex_encode(&buf), COMMIT_UPLOAD_SAVER_HEX);
}

#[test]
fn create_album_bytes_match_go() {
    let msg = CreateAlbum {
        album_name: "Test Album".to_string(),
        timestamp: TIMESTAMP,
        field3: 1,
        media_keys: vec![CreateAlbumField4 {
            field1: Some(CreateAlbumField4Field1 {
                media_key: "MEDIAKEY1".to_string(),
            }),
        }],
        field6: Some(CreateAlbumField6 {}),
        field7: Some(CreateAlbumField7 { field1: 3 }),
        device_info: Some(DeviceInfo {
            model: "Pixel XL".to_string(),
            make: "Google".to_string(),
            android_api_version: 28,
        }),
    };
    let mut buf = Vec::new();
    msg.encode(&mut buf);
    assert_eq!(hex_encode(&buf), CREATE_ALBUM_HEX);
}

#[test]
fn add_media_to_album_bytes_match_go() {
    let msg = AddMediaToAlbum {
        media_keys: vec!["MEDIAKEY1".to_string(), "MEDIAKEY2".to_string()],
        album_media_key: "ALBUMKEY".to_string(),
        field5: Some(AddMediaToAlbumField5 { field1: 2 }),
        device_info: Some(DeviceInfo {
            model: "Pixel XL".to_string(),
            make: "Google".to_string(),
            android_api_version: 28,
        }),
        timestamp: TIMESTAMP,
    };
    let mut buf = Vec::new();
    msg.encode(&mut buf);
    assert_eq!(hex_encode(&buf), ADD_MEDIA_TO_ALBUM_HEX);
}

// ---- Decode fixtures ----------------------------------------------------------

#[test]
fn commit_token_decodes() {
    let decoded = CommitToken::decode(&hex_decode(COMMIT_TOKEN_HEX)).expect("decode CommitToken");
    assert_eq!(decoded.field1, 2);
    assert_eq!(decoded.field2, OPAQUE_TOKEN.to_vec());
}

#[test]
fn remote_matches_media_key_path() {
    let resp = RemoteMatches::decode(&hex_decode(REMOTE_MATCHES_HEX)).expect("decode RemoteMatches");
    assert_eq!(resp.media_key(), Some("MEDIAKEY1"));
    // An empty response (hash not in library) yields no key, not an error.
    let empty = RemoteMatches::decode(&[]).expect("decode empty RemoteMatches");
    assert_eq!(empty.media_key(), None);
}

#[test]
fn create_media_items_response_first_media_key() {
    let resp = CreateMediaItemsResponse::decode(&hex_decode(CREATE_MEDIA_ITEMS_RESPONSE_HEX))
        .expect("decode CreateMediaItemsResponse");
    assert_eq!(resp.first_media_key(), Some("MEDIAKEY1"));
}

// ---- Scotty token validation (core/scotty_token.go) ----------------------------

#[test]
fn scotty_token_accepts_valid_envelope_and_keeps_raw_bytes() {
    let raw = hex_decode(COMMIT_TOKEN_HEX);
    let token = ScottyToken::parse(&raw).expect("valid Scotty token");
    // The raw envelope is preserved byte-for-byte: Live Photo commits embed
    // it unchanged (core/create_media_items.go), so no decode/re-encode.
    assert_eq!(token.raw(), raw.as_slice());
}

#[test]
fn scotty_token_allows_unknown_extra_fields() {
    // Go's wire walk ignores fields other than 1 and 2; only the counts and
    // shapes of fields 1/2 are validated. Append field 3 varint 7 (18 07).
    let mut raw = hex_decode(COMMIT_TOKEN_HEX);
    raw.extend_from_slice(&[0x18, 0x07]);
    assert!(ScottyToken::parse(&raw).is_ok());
}

#[test]
fn scotty_token_rejects_wrong_version() {
    // field 1 = 3 instead of 2.
    assert!(ScottyToken::parse(&hex_decode("08031204deadbeef")).is_err());
}

#[test]
fn scotty_token_rejects_duplicate_version_field() {
    assert!(ScottyToken::parse(&hex_decode("080208021204deadbeef")).is_err());
}

#[test]
fn scotty_token_rejects_empty_payload() {
    // field 2 present but zero-length.
    assert!(ScottyToken::parse(&hex_decode("08021200")).is_err());
}

#[test]
fn scotty_token_rejects_duplicate_payload() {
    assert!(ScottyToken::parse(&hex_decode("08021204deadbeef1204deadbeef")).is_err());
}

#[test]
fn scotty_token_rejects_wrong_wire_types() {
    // field 1 as length-delimited instead of varint.
    assert!(ScottyToken::parse(&hex_decode("0a0208021204deadbeef")).is_err());
    // field 2 as varint instead of bytes.
    assert!(ScottyToken::parse(&hex_decode("08021002")).is_err());
}

#[test]
fn scotty_token_rejects_truncated_and_empty() {
    assert!(ScottyToken::parse(&hex_decode("08021204dead")).is_err());
    assert!(ScottyToken::parse(&[]).is_err());
}

// ---- Golden file cross-check ----------------------------------------------------

/// The Go-generated golden file must agree with the hand-derived constants
/// above, line for line. If this test fails but the per-message tests pass
/// (or vice versa), one of the two derivations moved — investigate before
/// changing either; the server accepts the GO bytes.
#[test]
fn golden_file_matches_hand_derived_fixtures() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/golden.txt");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let golden: std::collections::HashMap<&str, &str> = text
        .lines()
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .filter_map(|l| l.split_once('='))
        .collect();

    let expected = [
        ("get_upload_token", GET_UPLOAD_TOKEN_HEX),
        ("hash_check", HASH_CHECK_HEX),
        ("commit_token", COMMIT_TOKEN_HEX),
        ("commit_upload", COMMIT_UPLOAD_HEX),
        ("commit_upload_saver", COMMIT_UPLOAD_SAVER_HEX),
        ("create_album", CREATE_ALBUM_HEX),
        ("add_media_to_album", ADD_MEDIA_TO_ALBUM_HEX),
        ("remote_matches", REMOTE_MATCHES_HEX),
        ("create_media_items_response", CREATE_MEDIA_ITEMS_RESPONSE_HEX),
        ("create_album_response", CREATE_ALBUM_RESPONSE_HEX),
    ];
    for (name, hex) in expected {
        assert_eq!(
            golden.get(name).copied(),
            Some(hex),
            "golden fixture {name} disagrees with the hand-derived bytes"
        );
    }
}
